spring:
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    password:
    url:
    username:

  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    database: oracle
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      javax.persistence.validation.mode: none
      hibernate:
        format_sql: true
        show_sql: false
        default_schema:

  sql:
    init:
      mode: never


server:
  port: 8103


info:
  tags:
    environment: test

bcm_api_url: "http://10.10.16.16:85"
token:
  banque: BBB
  password: 1234

feign:
  httpclient:
    disable-ssl-validation: true
