server:
  port: 8075
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/bcm
    username: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: update

    show-sql: false
    properties:
      javax.persistence.validation.mode: none
      hibernate:
        format_sql: true
        show_sql: false

bcm_api_url: "http://10.10.16.16:85"
token:
  banque: BBB
  password: 1234

logging:
  config: classpath:logback-spring.xml
